version: "3.9"
services:
  app:
    build: .
    image: gtk4-c-dev:latest
    container_name: gtk4-c-dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    working_dir: /work
    volumes:
      - .:/work
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    user: "${UID}:${GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
